# Generated by Django 5.2.6 on 2025-09-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=6, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('faculty', models.CharField(max_length=100)),
                ('semester', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('leave_type', models.CharField(choices=[('M', 'Medical_reason'), ('P', 'Personal_reason'), ('E', 'Emergency_reason')])),
                ('reason', models.TextField()),
                ('guardian_contact', models.CharField(max_length=13)),
                ('is_delete', models.BooleanField(default=False)),
                ('delete_time', models.DateTimeField(null=True)),
                ('student_email', models.EmailField(max_length=100)),
            ],
        ),
    ]
