# Generated by Django 6.0.5 on 2026-06-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='s_username',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='t_username',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Coordinator', 'Coordinator'), ('Teacher', 'Teacher')], max_length=20),
        ),
    ]
