# Generated by Django 5.2.6 on 2025-09-26 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_student_leave_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='StudentLeave',
        ),
    ]
