# Generated by Django 6.0.5 on 2026-06-12 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_s_username_student_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='password',
        ),
    ]
