# Generated by Django 5.2.6 on 2025-10-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_studentleave_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentleave',
            name='student_email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
