# Generated by Django 5.2.6 on 2025-10-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_studentleave_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentleave',
            name='roll_number',
            field=models.CharField(default='', max_length=6, unique=True),
        ),
    ]
