# Generated by Django 5.2.6 on 2025-10-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_studentleave_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentleave',
            name='roll_number',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='studentleave',
            name='student_email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
