# Generated by Django 5.2.6 on 2025-10-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_studentleave_roll_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentleave',
            name='roll_number',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
    ]
